export enum Experience {
  INTERESTED = 'INTERESTED',
  EXPERIENCED = 'EXPERIENCED',
  CHIEF_EXPERIENCED = 'CHIEF_EXPERIENCED',
  OUTSIDE_EXPERIENCED = 'OUTSIDE_EXPERIENCED',
}

export enum ExperienceName {
  INTERESTED = 'Interested',
  EXPERIENCED = 'Experienced',
  CHIEF_EXPERIENCED = 'Chief',
  OUTSIDE_EXPERIENCED = 'Outside',
}
