export enum Experience {
  INTERESTED,
  EXPERIENCED,
  CHIEF_EXPERIENCED,
  OUTSIDE_EXPERIENCED,
}

export enum ExperienceName {
  INTERESTED = 'INTERESTED',
  EXPERIENCED = 'EXPERIENCED',
  CHIEF_EXPERIENCED = 'CHIEF',
  OUTSIDE_EXPERIENCED = 'OUTSIDE',
}
