export enum Ministry {
  AGRI = 'AGRI',
  AF = 'AF',
  AG = 'AG',
  MCF = 'MCF',
  CITZ = 'CITZ',
  ECC = 'ECC',
  EMCR = 'EMCR',
  EMLI = 'EMLI',
  ENV = 'ENV',
  FIN = 'FIN',
  FOR = 'FOR',
  GCPE = 'GCPE',
  HLTH = 'HLTH',
  HOUS = 'HOUS',
  IRR = 'IRR',
  JEDI = 'JEDI',
  LBR = 'LBR',
  MMHA = 'MMHA',
  MUNI = 'MUNI',
  PREM = 'PREM',
  PSA = 'PSA',
  PSFS = 'PSFS',
  PSSG = 'PSSG',
  SDPR = 'SDPR',
  TACS = 'TACS',
  MOTI = 'MOTI',
  WLRS = 'WLRS',
}

export enum MinistryName {
  AF = 'Agriculture and Food',  
  AG = 'Attorney General',
  AGRI = 'Agriculture',
  MCF = 'Children and Family Development',
  CITZ = "Citizens' Services",
  ECC = 'Education and Child Care',
  EMCR = 'Emergency Management and Climate Readiness',
  EMLI = 'Energy, Mines and Low Carbon Innovation',
  ENV = 'Environment and Climate Change Strategy',
  FIN = 'Finance',
  GCPE = 'Government Communications and Public Engagement',
  FOR = 'Forests',
  HLTH = 'Health',
  HOUS = 'Housing',
  IRR = 'Indigenous Relations & Reconciliation',
  JEDI = 'Jobs, Economic Development and Innovation',
  LBR = 'Labour',
  MMHA = 'Mental Health and Addictions',
  MUNI = 'Municipal Affairs',
  PREM = 'Office of the Premier',
  PSA = 'Public Service Agency',
  PSFS = 'Post-Secondary Education and Future Skills',
  PSSG = 'Public Safety and Solicitor General',
  SDPR = 'Social Development and Poverty Reduction',
  TACS = 'Tourism, Arts, Culture and Sport',
  MOTI = 'Transportation and Infrastructure',
  WLRS = 'Water, Land and Resource Stewardship',

  
}
