export enum Ministry {
  AGRI = 'AGRI',
  AG = 'AG',
  MCF = 'MCF',
  CITZ = 'CITZ',
  ECC = 'ECC',
  EMCR = 'EMCR',
  EMLI = 'EMLI',
  ENV = 'ENV',
  FIN = 'FIN',
  FOR = 'FOR',
  HLTH = 'HLTH',
  HOUS = 'HOUS',
  IRR = 'IRR',
  JEDI = 'JEDI',
  LBR = 'LBR',
  MMHA = 'MMHA',
  MUNI = 'MUNI',
  PSFS = 'PSFS',
  PSSG = 'PSSG',
  SDPR = 'SDPR',
  TAC = 'TAC',
  MOTI = 'MOTI',
  WLRS = 'WLRS',
}

export enum MinistryName {
  AGRI = 'Agriculture and Food (AGRI)',
  AG = 'Attorney General (AG)',
  MCF = 'Children and Family Development (MCF)',
  CITZ = 'Citizens\' Services (CITZ)',
  ECC = 'Education and Child Care (ECC)',
  EMCR = 'Emergency Management and Climate Readiness (EMCR)',
  EMLI = 'Energy, Mines and Low Carbon Innovation (EMLI)',
  ENV = 'Environment and Climate Change Strategy (ENV)',
  FIN = 'Finance (FIN)',
  FOR = 'Forests (FOR)',
  HLTH = 'Health (HLTH)',
  HOUS = 'Housing (HOUS)',
  IRR = 'Indigenous Relations & Reconciliation (IRR)',
  JEDI = 'Jobs, Economic Development and Innovation (JEDI)',
  LBR = 'Labour (LBR)',
  MMHA = 'Mental Health and Addictions (MMHA)',
  MUNI = 'Municipal Affairs (MUNI)',
  PSFS = 'Post-Secondary Education and Future Skills (PSFS)',
  PSSG = 'Public Safety and Solicitor General (PSSG)',
  SDPR = 'Social Development and Poverty Reduction (SDPR)',
  TAC = 'Tourism, Arts, Culture and Sport (TAC)',
  MOTI = 'Transportation and Infrastructure (MOTI)',
  WLRS = 'Water, Land and Resource Stewardship (WLRS)',
}