export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum AvailabilityTypeStatus {
  ALL = 'ALL',
  NEW = 'NEW',
  SUPERVISOR_APPROVED = 'SUPERVISOR_APPROVED',
  OTHER = 'OTHER',
  MEMBER_DENIED = 'MEMBER_DENIED',
  MISSED = 'MISSED',
  SUPERVISOR_DENIED = 'SUPERVISOR_DENIED',
}
