export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum AvailabilityTypeStatus {
  ALL = 'ALL',
  NEW = 'NEW',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MEMBER_COMMITTED = 'MEMBER_COMMITTED',
  MEMBER_DENIED = 'MEMBER_DENIED',
  MEMBER_NO_RESPONSE = 'MEMBER_NO_RESPONSE',
  SUPERVISOR_DENIED = 'SUPERVISOR_DENIED',
  PENDING = 'PENDING',
  OTHER = 'OTHER',
}
