export enum TravelPreference {
  REMOTE_ONLY = 'REMOTE_ONLY',
  WILLING_TO_TRAVEL_HOME_LOCATION = 'WILLING_TO_TRAVEL_HOME_LOCATION',
  WILLING_TO_TRAVEL_FIRE_ZONE = 'WILLING_TO_TRAVEL_FIRE_ZONE',
  WILLING_TO_TRAVEL_REGION = 'WILLING_TO_TRAVEL_REGION',
  WILLING_TO_TRAVEL_ANYWHERE = 'WILLING_TO_TRAVEL_ANYWHERE',
}