export enum WorkLocation {
  HUNDRED_MILE_HOUSE,
  HUNDRED_FIFTY_MILE_HOUSE,
  ABBOTSFORD,
  BRENTWOOD_BAY,
  BURNABY,
  BURNS_LAKE,
  CAMPBELL_RIVER,
  CASTLEGAR,
  COQUITLAM,
  COURTENAY,
  CRANBROOK,
  DAWSON_CREEK,
  DUNCAN,
  ELKFORD,
  ENDERBY,
  FORT_ST_JOHN,
  FORT_NELSON,
  KAMLOOPS,
  KELOWNA,
  LANGFORD,
  LANGLEY,
  LILLOOET,
  MACKENZIE,
  MAPLE_RIDGE,
  MERRITT,
  MILL_BAY,
  MISSION,
  NANAIMO,
  NELSON,
  NEW_WESTMINSTER,
  NORTH_VANCOUVER,
  PARKSVILLE,
  PENTICTON,
  PORT_ALBERNI,
  PORT_MCNEIL,
  PRINCE_GEORGE,
  QUESNEL,
  REVELSTOKE,
  RICHMOND,
  SAANICH,
  SAANICHTON,
  SALMON_ARM,
  SECHELT,
  SIDNEY,
  SMITHERS,
  SORRENTO,
  SURREY,
  TERRACE,
  UCLUELET,
  VANCOUVER,
  VICTORIA,
  WHISTLER,
  WILLIAMS_LAKE,
}

export enum WorkLocationName {
  HUNDRED_MILE_HOUSE = '100 Mile House',
  HUNDRED_FIFTY_MILE_HOUSE = '150 Mile House',
  ABBOTSFORD = 'Abbotsford',
  BRENTWOOD_BAY = 'Brentwood Bay',
  BURNABY = 'Burnaby',
  BURNS_LAKE = 'Burns Lake',
  CAMPBELL_RIVER = 'Campbell River',
  CASTLEGAR = 'Castlegar',
  COQUITLAM = 'Coquitlam',
  COURTENAY = 'Courtenay',
  CRANBROOK = 'Cranbrook',
  DAWSON_CREEK = 'Dawson Creek',
  DUNCAN = 'Duncan',
  ELKFORD = 'Elkford',
  ENDERBY = 'Enderby',
  FORT_ST_JOHN = 'Fort St. John',
  FORT_NELSON = 'Fort Nelson',
  KAMLOOPS = 'Kamloops',
  KELOWNA = 'Kelowna',
  LANGFORD = 'Langford',
  LANGLEY = 'Langley',
  LILLOOET = 'Lillooet',
  MACKENZIE = 'Mackenzie',
  MAPLE_RIDGE = 'Maple Ridge',
  MERRITT = 'Merritt',
  MILL_BAY = 'Mill Bay',
  MISSION = 'Mission',
  NANAIMO = 'Nanaimo',
  NELSON = 'Nelson',
  NEW_WESTMINSTER = 'New Westminster',
  NORTH_VANCOUVER = 'North Vancouver',
  PARKSVILLE = 'Parksville',
  PENTICTON = 'Penticton',
  PORT_ALBERNI = 'Port Alberni',
  PORT_MCNEIL = 'Port McNeil',
  PRINCE_GEORGE = 'Prince George',
  QUESNEL = 'Quesnel',
  REVELSTOKE = 'Revelstoke',
  RICHMOND = 'Richmond',
  SAANICH = 'Saanich',
  SAANICHTON = 'Saanichton',
  SALMON_ARM = 'Salmon Arm',
  SECHELT = 'Sechelt',
  SIDNEY = 'Sidney',
  SMITHERS = 'Smithers',
  SORRENTO = 'Sorrento',
  SURREY = 'Surrey',
  TERRACE = 'Terrace',
  UCLUELET = 'Ucluelet',
  VANCOUVER = 'Vancouver',
  VICTORIA = 'Victoria',
  WHISTLER = 'Whistler',
  WILLIAMS_LAKE = 'Williams Lake',
}