export const data = {
  bcws: {
    tools: [],
    sections: {
      COMMAND: [
        {
          role: {
            id: 46,
            name: 'Information  Officer',
            section: 'Command',
            enumName: 'INFORMATION_OFFICER',
          },
          experience: 'PREVIOUSLY_DEPLOYED',
        },
        {
          role: {
            id: 46,
            name: 'Information  Officer',
            section: 'Command',
            enumName: 'INFORMATION_OFFICER',
          },
          experience: 'INTERESTED',
        },
      ],
      AVIATION: [],
      PLANNING: [],
      LOGISTICS: [],
      OPERATIONS: [],
      FINANCE_ADMIN: [],
    },
    languages: [],
    paylistId: '999-999',
    employeeId: '555555',
    certificates: [],
    liaisonUnknown: true,
    firstChoiceSection: 'COMMAND',
    secondChoiceSection: '',
    emergencyContactLastName: 'Brown',
    emergencyContactFirstName: 'Chelsea',
    emergencyContactPhoneNumber: '(777) 777-7777',
    emergencyContactRelationship: 'Friend',
  },
  emcr: {
    functions: {
      '1': true,
      '2': false,
      '3': false,
      '4': false,
      '5': false,
      '6': false,
      '7': false,
      '8': false,
      '9': false,
      '10': false,
    },
    experience: {
      peccExperience: true,
      preocExperience: true,
      emergencyExperience: true,
      firstNationsWorking: true,
    },
  },
  next: true,
  next1: true,
  next2: true,
  next3: true,
  submit: true,
  ackBoth: {
    ack: true,
    parQ: true,
    orientation: true,
    supervisorApproval: true,
    willingnessStatement: true,
  },
  lateEntry: false,
  personnel: {
    dl: [],
    pfa: 'no',
    email: 'chelsea.brown@gov.bc.ca',
    program: 'BOTH',
    division: 'none',
    jobTitle: 'asd',
    lastName: 'Brown',
    ministry: {
      label: 'Attorney General',
      value: 'AG',
    },
    firstName: 'Chelsea',
    workPhone: '',
    deployment: 'willingToTravel',
    homeLocation: {
      id: 65,
      region: 'NEA',
      fireCentre: 'CARIBOO',
      locationName: '100 Mile House',
    },
    primaryPhone: '(777) 777-7777',
    workLocation: {
      id: 3,
      region: 'NEA',
      fireCentre: 'CARIBOO',
      locationName: 'Alexis Creek',
    },
    firstAidLevel: '',
    secondaryPhone: '',
    supervisorEmail: 'chelsea.brown@gov.bc.ca',
    unionMembership: 'BCGEU',
    supervisorLastName: 'Brown',
    supervisorFirstName: 'Chelsea',
    supervisorPhoneNumber: '(250) 891-4016',
  },
  previous1: false,
  previous2: false,
  previous3: false,
  fieldDataAPI: {
    certs: [
      {
        id: 1,
        name: 'Forklift - Certified',
      },
      {
        id: 3,
        name: 'Radio Operator',
      },
      {
        id: 4,
        name: 'Volunteer Fire Dept',
      },
      {
        id: 5,
        name: 'Quad/ATV',
      },
      {
        id: 6,
        name: 'Food Safe Level I',
      },
      {
        id: 7,
        name: 'Food Safe Level II',
      },
    ],
    tools: [
      {
        id: 1,
        name: 'ADOBE',
        fullName: 'Adobe Pro',
      },
      {
        id: 2,
        name: 'CAS',
        fullName: 'Corporate Accounting System (CAS)',
      },
      {
        id: 3,
        name: 'DEC',
        fullName: 'Daily Estimated Costs/Wildfire Costing (DEC/WFCST)',
      },
      {
        id: 4,
        name: 'EXCEL',
        fullName: 'Excel',
      },
      {
        id: 5,
        name: 'FACE',
        fullName: 'Fire Analysis Cost Estimate (FACE)',
      },
      {
        id: 6,
        name: 'IMIS',
        fullName: 'Inventory Management (IMIS)',
      },
      {
        id: 7,
        name: 'RRT',
        fullName: 'Resource Request Tracking (RRT)',
      },
      {
        id: 8,
        name: 'VISIO',
        fullName: 'Visio',
      },
    ],
    sections: {
      COMMAND: [
        {
          id: 45,
          name: 'Information Assistant',
          section: 'Command',
          enumName: 'INFORMATION_ASSISTANT',
        },
        {
          id: 46,
          name: 'Information  Officer',
          section: 'Command',
          enumName: 'INFORMATION_OFFICER',
        },
        {
          id: 47,
          name: 'Liaison Officer',
          section: 'Command',
          enumName: 'LIAISON_OFFICER',
        },
        {
          id: 48,
          name: 'Safety Officer',
          section: 'Command',
          enumName: 'SAFETY_OFFICER',
        },
      ],
      AVIATION: [
        {
          id: 49,
          name: 'Aviation Assistant',
          section: 'Aviation',
          enumName: 'AVIATION_ASSISTANT',
        },
        {
          id: 50,
          name: 'Heli Coordinator',
          section: 'Aviation',
          enumName: 'HELI_COORDINATOR',
        },
        {
          id: 51,
          name: 'Helibase Manager',
          section: 'Aviation',
          enumName: 'HELIBASE_MANAGER',
        },
      ],
      PLANNING: [
        {
          id: 1,
          name: 'Demobilization Unit Leader',
          section: 'Planning',
          enumName: 'DEMOBILIZATION_UNIT_LEADER',
        },
        {
          id: 2,
          name: 'Documentation Unit Leader',
          section: 'Planning',
          enumName: 'DOCUMENTATION_UNIT_LEADER',
        },
        {
          id: 3,
          name: 'Fire Behaviour Specialist',
          section: 'Planning',
          enumName: 'FIRE_BEHAVIOUR_SPECIALIST',
        },
        {
          id: 4,
          name: 'GIS Specialist',
          section: 'Planning',
          enumName: 'GIS_SPECIALIST',
        },
        {
          id: 5,
          name: 'Planning Assistant',
          section: 'Planning',
          enumName: 'PLANNING_ASSISTANT',
        },
        {
          id: 7,
          name: 'Plans Officer',
          section: 'Planning',
          enumName: 'PLANS_OFFICER',
        },
        {
          id: 8,
          name: 'Plans Section Chief',
          section: 'Planning',
          enumName: 'PLANS_SECTION_CHIEF',
        },
        {
          id: 9,
          name: 'Rehab Specialist',
          section: 'Planning',
          enumName: 'REHAB_SPECIALIST',
        },
        {
          id: 10,
          name: 'Resource Unit Leader',
          section: 'Planning',
          enumName: 'RESOURCE_UNIT_LEADER',
        },
        {
          id: 11,
          name: 'Situation Unit Leader',
          section: 'Planning',
          enumName: 'SITUATION_UNIT_LEADER',
        },
      ],
      LOGISTICS: [
        {
          id: 12,
          name: 'Asset Management',
          section: 'Logistics',
          enumName: 'ASSET_MANAGEMENT',
        },
        {
          id: 13,
          name: 'Camp Manager',
          section: 'Logistics',
          enumName: 'CAMP_MANAGER',
        },
        {
          id: 14,
          name: 'Communication Unit Leader',
          section: 'Logistics',
          enumName: 'COMMUNICATION_UNIT_LEADER',
        },
        {
          id: 15,
          name: 'Contract Monitor',
          section: 'Logistics',
          enumName: 'CONTRACT_MONITOR',
        },
        {
          id: 16,
          name: 'Dispatcher',
          section: 'Logistics',
          enumName: 'DISPATCHER',
        },
        {
          id: 17,
          name: 'Facilities Unit Leader',
          section: 'Logistics',
          enumName: 'FACILITIES_UNIT_LEADER',
        },
        {
          id: 18,
          name: 'Food Unit Leader',
          section: 'Logistics',
          enumName: 'FOOD_UNIT_LEADER',
        },
        {
          id: 19,
          name: 'Ground Support Unit Leader',
          section: 'Logistics',
          enumName: 'GROUND_SUPPORT_UNIT_LEADER',
        },
        {
          id: 20,
          name: 'Logistics Assistant',
          section: 'Logistics',
          enumName: 'LOGISTICS_ASSISTANT',
        },
        {
          id: 21,
          name: 'Logistics Officer',
          section: 'Logistics',
          enumName: 'LOGISTICS_OFFICER',
        },
        {
          id: 22,
          name: 'Logistics Section Chief',
          section: 'Logistics',
          enumName: 'LOGISTICS_SECTION_CHIEF',
        },
        {
          id: 23,
          name: 'Medical Unit Leader',
          section: 'Logistics',
          enumName: 'MEDICAL_UNIT_LEADER',
        },
        {
          id: 24,
          name: 'Service Branch Director',
          section: 'Logistics',
          enumName: 'SERVICE_BRANCH_DIRECTOR',
        },
        {
          id: 25,
          name: 'Supply Unit Leader',
          section: 'Logistics',
          enumName: 'SUPPLY_UNIT_LEADER',
        },
        {
          id: 26,
          name: 'Support Branch Director',
          section: 'Logistics',
          enumName: 'SUPPORT_BRANCH_DIRECTOR',
        },
        {
          id: 27,
          name: 'Warehouse Manager',
          section: 'Logistics',
          enumName: 'WAREHOUSE_MANAGER',
        },
      ],
      OPERATIONS: [
        {
          id: 39,
          name: 'Division Supervisor',
          section: 'Operations',
          enumName: 'DIVISION_SUPERVISOR',
        },
        {
          id: 40,
          name: 'Equipment Branch Director',
          section: 'Operations',
          enumName: 'EQUIPMENT_BRANCH_DIRECTOR',
        },
        {
          id: 41,
          name: 'Equipment Group Supervisor',
          section: 'Operations',
          enumName: 'EQUIPMENT_GROUP_SUPERVISOR',
        },
        {
          id: 42,
          name: 'Line Locator',
          section: 'Operations',
          enumName: 'LINE_LOCATOR',
        },
        {
          id: 43,
          name: 'Strike Team Leader',
          section: 'Operations',
          enumName: 'STRIKE_TEAM_LEADER',
        },
        {
          id: 44,
          name: 'Task Force Leader',
          section: 'Operations',
          enumName: 'TASK_FORCE_LEADER',
        },
      ],
      FINANCE_ADMIN: [
        {
          id: 28,
          name: 'Accounts Payable',
          section: 'Finance Admin',
          enumName: 'ACCOUNTS_PAYABLE',
        },
        {
          id: 29,
          name: 'Compensation & Claims Unit Leader',
          section: 'Finance Admin',
          enumName: 'COMPENSATION_CLAIMS_UNIT_LEADER',
        },
        {
          id: 30,
          name: 'Contract Administration',
          section: 'Finance Admin',
          enumName: 'CONTRACT_ADMINISTRATION',
        },
        {
          id: 31,
          name: 'Cost Unit Leader',
          section: 'Finance Admin',
          enumName: 'COST_UNIT_LEADER',
        },
        {
          id: 32,
          name: 'Finance Assistant',
          section: 'Finance Admin',
          enumName: 'FINANCE_ASSISTANT',
        },
        {
          id: 33,
          name: 'Finance Liaison',
          section: 'Finance Admin',
          enumName: 'FINANCE_LIAISON',
        },
        {
          id: 34,
          name: 'Finance Officer',
          section: 'Finance Admin',
          enumName: 'FINANCE_OFFICER',
        },
        {
          id: 35,
          name: 'Finance Section Chief',
          section: 'Finance Admin',
          enumName: 'FINANCE_SECTION_CHIEF',
        },
        {
          id: 36,
          name: 'Procurement Unit Leader',
          section: 'Finance Admin',
          enumName: 'PROCUREMENT_UNIT_LEADER',
        },
        {
          id: 37,
          name: 'Time Recorder',
          section: 'Finance Admin',
          enumName: 'TIME_RECORDER',
        },
        {
          id: 38,
          name: 'Time Unit Leader',
          section: 'Finance Admin',
          enumName: 'TIME_UNIT_LEADER',
        },
      ],
    },
    locations: [
      {
        id: 65,
        region: 'NEA',
        fireCentre: 'CARIBOO',
        locationName: '100 Mile House',
      },
      {
        id: 66,
        region: 'NEA',
        fireCentre: 'CARIBOO',
        locationName: '150 Mile House',
      },
      {
        id: 5,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Abbotsford',
      },
      {
        id: 3,
        region: 'NEA',
        fireCentre: 'CARIBOO',
        locationName: 'Alexis Creek',
      },
      {
        id: 90,
        region: 'NWE',
        fireCentre: 'CARIBOO',
        locationName: 'Anahim Lake',
      },
      {
        id: 34,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Atlin',
      },
      {
        id: 13,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Bella Coola',
      },
      {
        id: 44,
        region: 'CTL',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Blue River',
      },
      {
        id: 68,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Bonnington Falls',
      },
      {
        id: 14,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Boston Bar',
      },
      {
        id: 59,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Brentwood Bay',
      },
      {
        id: 72,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Burnaby',
      },
      {
        id: 31,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Burns Lake',
      },
      {
        id: 7,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Campbell River',
      },
      {
        id: 69,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Castlegar',
      },
      {
        id: 45,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Chetwynd',
      },
      {
        id: 15,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Chilliwack',
      },
      {
        id: 28,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Clearwater',
      },
      {
        id: 73,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Coquitlam',
      },
      {
        id: 82,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Courtenay',
      },
      {
        id: 49,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Cranbrook',
      },
      {
        id: 16,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Cultus Lake',
      },
      {
        id: 83,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Cumberland',
      },
      {
        id: 39,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Dawson Creek',
      },
      {
        id: 35,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Dease Lake',
      },
      {
        id: 8,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Duncan',
      },
      {
        id: 70,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Elkford',
      },
      {
        id: 57,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Enderby',
      },
      {
        id: 60,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Esquimalt',
      },
      {
        id: 40,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Fort Nelson',
      },
      {
        id: 46,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Fort St. James',
      },
      {
        id: 41,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Fort St. John',
      },
      {
        id: 53,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Golden',
      },
      {
        id: 54,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Grand Forks',
      },
      {
        id: 36,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Hazelton',
      },
      {
        id: 37,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Houston',
      },
      {
        id: 55,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Invermere',
      },
      {
        id: 21,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Kamloops',
      },
      {
        id: 22,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Kelowna',
      },
      {
        id: 50,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Kimberley',
      },
      {
        id: 61,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Langford',
      },
      {
        id: 74,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Langley',
      },
      {
        id: 27,
        region: 'SWE',
        fireCentre: 'KAMLOOPS',
        locationName: 'Lillooet',
      },
      {
        id: 29,
        region: 'SWE',
        fireCentre: 'KAMLOOPS',
        locationName: 'Lytton',
      },
      {
        id: 67,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Mackenzie',
      },
      {
        id: 75,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Maple Ridge',
      },
      {
        id: 17,
        region: 'NWE',
        fireCentre: 'COASTAL',
        locationName: 'Masset',
      },
      {
        id: 23,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Merritt',
      },
      {
        id: 84,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Mill Bay',
      },
      {
        id: 76,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Mission',
      },
      {
        id: 56,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Nakusp',
      },
      {
        id: 9,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Nanaimo',
      },
      {
        id: 51,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Nelson',
      },
      {
        id: 77,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'New Westminster',
      },
      {
        id: 78,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'North Vancouver',
      },
      {
        id: 10,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Parksville',
      },
      {
        id: 18,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Pemberton',
      },
      {
        id: 24,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Penticton',
      },
      {
        id: 11,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Port Alberni',
      },
      {
        id: 85,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Port McNeil',
      },
      {
        id: 19,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Powell River',
      },
      {
        id: 42,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Prince George',
      },
      {
        id: 38,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Prince Rupert',
      },
      {
        id: 30,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Princeton',
      },
      {
        id: 86,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Qualicum Beach',
      },
      {
        id: 1,
        region: 'NEA',
        fireCentre: 'CARIBOO',
        locationName: 'Quesnel',
      },
      {
        id: 71,
        region: 'SEA',
        fireCentre: 'SOUTHEAST',
        locationName: 'Revelstoke',
      },
      {
        id: 79,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Richmond',
      },
      {
        id: 62,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Saanich',
      },
      {
        id: 63,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Saanichton',
      },
      {
        id: 25,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Salmon Arm',
      },
      {
        id: 12,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Sechelt',
      },
      {
        id: 64,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Sidney',
      },
      {
        id: 32,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Smithers',
      },
      {
        id: 87,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Sooke',
      },
      {
        id: 58,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Sorrento',
      },
      {
        id: 20,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Squamish',
      },
      {
        id: 80,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Surrey',
      },
      {
        id: 89,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Telkwa',
      },
      {
        id: 33,
        region: 'NWE',
        fireCentre: 'NORTHWEST',
        locationName: 'Terrace',
      },
      {
        id: 88,
        region: 'VIC',
        fireCentre: 'COASTAL',
        locationName: 'Ucluelet',
      },
      {
        id: 48,
        region: 'NEA',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Valemount',
      },
      {
        id: 6,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Vancouver',
      },
      {
        id: 43,
        region: 'NWE',
        fireCentre: 'PRINCE_GEORGE',
        locationName: 'Vanderhoof',
      },
      {
        id: 26,
        region: 'CTL',
        fireCentre: 'KAMLOOPS',
        locationName: 'Vernon',
      },
      {
        id: 4,
        region: 'HQ',
        fireCentre: 'COASTAL',
        locationName: 'Victoria',
      },
      {
        id: 81,
        region: 'SWE',
        fireCentre: 'COASTAL',
        locationName: 'Whistler',
      },
      {
        id: 2,
        region: 'NEA',
        fireCentre: 'CARIBOO',
        locationName: 'Williams Lake',
      },
    ],
    ministries: [
      {
        label: 'Agriculture and Food',
        value: 'AF',
      },
      {
        label: 'Attorney General',
        value: 'AG',
      },
      {
        label: 'Children and Family Development',
        value: 'MCF',
      },
      {
        label: "Citizens' Services",
        value: 'CITZ',
      },
      {
        label: 'Education and Child Care',
        value: 'ECC',
      },
      {
        label: 'Emergency Management and Climate Readiness',
        value: 'EMCR',
      },
      {
        label: 'Energy, Mines and Low Carbon Innovation',
        value: 'EMLI',
      },
      {
        label: 'Environment and Climate Change Strategy',
        value: 'ENV',
      },
      {
        label: 'Finance',
        value: 'FIN',
      },
      {
        label: 'Forests',
        value: 'FOR',
      },
      {
        label: 'Government Communications and Public Engagement',
        value: 'GCPE',
      },
      {
        label: 'Health',
        value: 'HLTH',
      },
      {
        label: 'Housing',
        value: 'HOUS',
      },
      {
        label: 'Indigenous Relations & Reconciliation',
        value: 'IRR',
      },
      {
        label: 'Jobs, Economic Development and Innovation',
        value: 'JEDI',
      },
      {
        label: 'Labour',
        value: 'LBR',
      },
      {
        label: 'Mental Health and Addictions',
        value: 'MMHA',
      },
      {
        label: 'Municipal Affairs',
        value: 'MUNI',
      },
      {
        label: 'Office of the Premier',
        value: 'PREM',
      },
      {
        label: 'Public Service Agency',
        value: 'PSA',
      },
      {
        label: 'Post-Secondary Education and Future Skills',
        value: 'PSFS',
      },
      {
        label: 'Public Safety and Solicitor General',
        value: 'PSSG',
      },
      {
        label: 'Social Development and Poverty Reduction',
        value: 'SDPR',
      },
      {
        label: 'Tourism, Arts, Culture and Sport',
        value: 'TACS',
      },
      {
        label: 'Transportation and Infrastructure',
        value: 'MOTI',
      },
      {
        label: 'Water, Land and Resource Stewardship',
        value: 'WLRS',
      },
    ],
  },
};
