FROM node:20.10.0-alpine

WORKDIR /usr/src/app

COPY ./*.json .

RUN npm config set cache /usr/src --global
RUN npm pkg delete scripts.prepare
RUN npm ci

COPY ./ .

RUN npm run build --production

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

CMD ["npm", "run", "start"]