###################
# BUILD FOR PRODUCTION
###################
FROM node:20-alpine AS build
WORKDIR /app
COPY  package.json ./
COPY server.js .
RUN npm pkg delete scripts.prepare
RUN npm install --omit=dev
COPY . .
ENV NODE_ENV production
RUN npm run build

###################
# PRODUCTION
###################

FROM node:20-alpine AS production
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/build ./build
COPY --from=build /app/server.js .
CMD [ "node", "server.js" ]