##################
# BUILD FOR CI TESTS
###################
# Only needed if running cypress inside the container
FROM cypress/included:latest



ENV PATH $PATH:/app/node_modules/.bin

WORKDIR /app
ENV PORT 3000

COPY package*.json . 
COPY . . 

RUN npm ci 

EXPOSE 3000