export enum District {
  DQU = 'DQU',
  DCC = 'DCC',
  DMH = 'DMH',
  DCK = 'DCK',
  DQC = 'DQC',
  DSQ = 'DSQ',
  DSC = 'DSC',
  DSI = 'DSI',
  DCR = 'DCR',
  DNI = 'DNI',
  DKA = 'DKA',
  DOS = 'DOS',
  DCS = 'DCS',
  DND = 'DND',
  DSS = 'DSS',
  DKM = 'DKM',
  DPG = 'DPG',
  DVA = 'DVA',
  DJA = 'DJA',
  DMK = 'DMK',
  DPC = 'DPC',
  DFN = 'DFN',
  DRM = 'DRM',
  DSE = 'DSE',
}

export enum DistrictName {
  DQU = 'Quesnel',
  DCC = 'Cariboo-Chilcotin',
  DMH = '100 Mile House',
  DCK = 'Chilliwack',
  DQC = 'Haida-Gwaii',
  DSQ = 'Sea to Sky',
  DSC = 'Sunshine Coast',
  DSI = 'South Island',
  DCR = 'Campbell River',
  DNI = 'North Island-Central Coast',
  DKA = 'Thompson Rivers',
  DOS = 'Okanagan Shuswap',
  DCS = 'Cascades',
  DND = 'Nadina',
  DSS = 'Skeena Stikine',
  DKM = 'Coast Mountains',
  DPG = 'Prince George',
  DVA = 'Vanderhoof',
  DJA = 'Fort St. James',
  DMK = 'MacKenzie',
  DPC = 'Peace',
  DFN = 'Fort Nelson',
  DRM = 'Rocky Mountain',
  DSE = 'Selkirk',
}
