export enum BcwsRole {
  Demobilization_Unit_Leader = 'Demobilization Unit Leader ',
  Documentation_Unit_Leader = 'Documentation Unit Leader',
  Fire_Behaviour_Specialist = 'Fire Behaviour Specialist ',
  GIS_Specialist = 'GIS Specialist',
  Planning_Assistant = 'Planning Assistant ',
  Plans_Officer = 'Plans Officer ',
  Plans_Section_Chief = 'Plans Section Chief ',
  Rehab_Specialist = 'Rehab Specialist ',
  Resource_Unit_Leader = 'Resource Unit Leader ',
  Situation_Unit_Leader = 'Situation Unit Leader ',
  Asset_management = 'Asset management ',
  Camp_Manager = 'Camp Manager ',
  Communication_Unit_Leader = 'Communication Unit Leader ',
  Contract_Monitor = 'Contract Monitor ',
  Dispatcher = 'Dispatcher ',
  Facilities_Unit_Leader = 'Facilities Unit Leader ',
  Food_Unit_Leader = 'Food Unit Leader ',
  Ground_Support_Unit_Leader = 'Ground Support Unit Leader ',
  Logistics_Assistant = 'Logistics Assistant ',
  Logistics_Officer = 'Logistics Officer ',
  Logistics_Section_Chief = 'Logistics Section Chief ',
  Medical_Unit_Leader = 'Medical Unit Leader ',
  Service_Branch_Director = 'Service Branch Director ',
  Supply_Unit_Leader = 'Supply Unit Leader ',
  Support_Branch_Director = 'Support Branch Director ',
  Warehouse_Manager = 'Warehouse Manager',
  Accounts_Payable = 'Accounts Payable ',
  Compensation_Claims_Unit_Leader = 'Compensation & Claims Unit Leader ',
  Contract_Administration = 'Contract Administration ',
  Cost_Unit_Leader = 'Cost Unit Leader ',
  Finance_Assistant = 'Finance Assistant ',
  Finance_Liaison = 'Finance Liaison ',
  Finance_Officer = 'Finance Officer ',
  Finance_Section_Chief = 'Finance Section Chief ',
  Procurement_Unit_Leader = 'Procurement Unit Leader ',
  Time_Recorder = 'Time Recorder ',
  Time_Unit_Leader = 'Time Unit Leader ',
  Division_Supervisor = 'Division Supervisor ',
  Equipment_Branch_Director = 'Equipment Branch Director ',
  Equipment_Group_Supervisor = 'Equipment Group Supervisor ',
  Line_Locator = 'Line Locator ',
  Strike_Team_Leader = 'Strike Team Leader ',
  Task_Force_Leader = 'Task Force Leader ',
  Information_Assistant = 'Information Assistant ',
  Information_Officer = 'Information  Officer ',
  Liaison_Officer = 'Liaison Officer ',
  Safety_Officer = 'Safety Officer ',
  Aviation_Assistant = 'Aviation Assistant ',
  Heli_Coordinator = 'Heli Coordinator ',
  Helibase_Manager = 'Helibase Manager ',
}

export enum Section {
  PLANNING = 'PLANNING',
  LOGISTICS = 'LOGISTICS',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  OPERATIONS = 'OPERATIONS',
  COMMAND = 'COMMAND',
  AVIATION = 'AVIATION',
}

export const sections = {
  [Section.PLANNING]: [
    BcwsRole.Demobilization_Unit_Leader,
    BcwsRole.Documentation_Unit_Leader,
    BcwsRole.Fire_Behaviour_Specialist,
    BcwsRole.GIS_Specialist,
    BcwsRole.Planning_Assistant,
    BcwsRole.Planning_Assistant,
    BcwsRole.Plans_Officer,
    BcwsRole.Plans_Section_Chief,
    BcwsRole.Rehab_Specialist,
    BcwsRole.Resource_Unit_Leader,
    BcwsRole.Situation_Unit_Leader,
  ],
  [Section.LOGISTICS]: [
    BcwsRole.Asset_management,
    BcwsRole.Camp_Manager,
    BcwsRole.Communication_Unit_Leader,
    BcwsRole.Contract_Monitor,
    BcwsRole.Dispatcher,
    BcwsRole.Facilities_Unit_Leader,
    BcwsRole.Food_Unit_Leader,
    BcwsRole.Ground_Support_Unit_Leader,
    BcwsRole.Logistics_Assistant,
    BcwsRole.Liaison_Officer,
    BcwsRole.Logistics_Section_Chief,
    BcwsRole.Medical_Unit_Leader,
    BcwsRole.Service_Branch_Director,
    BcwsRole.Supply_Unit_Leader,
    BcwsRole.Support_Branch_Director,
    BcwsRole.Warehouse_Manager,
  ],
  [Section.FINANCE_ADMIN]: [
    BcwsRole.Accounts_Payable,
    BcwsRole.Compensation_Claims_Unit_Leader,
    BcwsRole.Contract_Administration,
    BcwsRole.Cost_Unit_Leader,
    BcwsRole.Finance_Assistant,
    BcwsRole.Finance_Liaison,
    BcwsRole.Finance_Officer,
    BcwsRole.Finance_Section_Chief,
    BcwsRole.Procurement_Unit_Leader,
    BcwsRole.Time_Recorder,
    BcwsRole.Time_Unit_Leader,
  ],
  [Section.OPERATIONS]: [
    BcwsRole.Division_Supervisor,
    BcwsRole.Equipment_Branch_Director,
    BcwsRole.Equipment_Group_Supervisor,
    BcwsRole.Line_Locator,
    BcwsRole.Strike_Team_Leader,
    BcwsRole.Task_Force_Leader,
  ],
  [Section.COMMAND]: [
    BcwsRole.Information_Assistant,
    BcwsRole.Information_Officer,
    BcwsRole.Liaison_Officer,
    BcwsRole.Safety_Officer,
  ],
  [Section.AVIATION]: [
    BcwsRole.Aviation_Assistant,
    BcwsRole.Heli_Coordinator,
    BcwsRole.Helibase_Manager,
  ],
};
