###################
# BUILD FOR LOCAL
###################
FROM node:20.10.0-alpine


WORKDIR /usr/src/app

COPY package*.json .

COPY . .

RUN npm install

ENV NODE_ENV development
ENV PORT 3000
ENV ENV dev


EXPOSE 3000

# Start the server using the production build
ENTRYPOINT ["/bin/sh", "-c", "npm run start:dev"]

