import { ICS_TRAINING_NAME } from '../common/const';

export const insertTrainingSql = `INSERT INTO public."emcr_training" ("id", "name") VALUES (1, '${ICS_TRAINING_NAME}');`;

export const insertPersonnelTrainingSql = `
INSERT INTO public."emcr_personnel_training" ("personnel_id", "training_id")
SELECT personnel_id as "personnel_id", 1 as "training_id" FROM public."emcr_personnel" WHERE status = 'ACTIVE';
`;

export const functionSql = `INSERT INTO public."emcr_function" (name,abbreviation) VALUES
	 ('Operations','Ops'),
	 ('Emergency Support Services','ESS'),
	 ('First Nations','FN'),
	 ('Finance','Fin'),
	 ('Liaison','Liaison'),
	 ('Logistics','Logs'),
	 ('Planning','Plans'),
	 ('Advanced Planning Unit','APU'),
	 ('Recovery','Recovery'),
	 ('Deputy Director','DDir');`;

export const rolesSql = `INSERT INTO public.bcws_role (id,"name","section") VALUES
	 (1,'DEMOBILIZATION_UNIT_LEADER','PLANNING'),
	 (2,'DOCUMENTATION_UNIT_LEADER','PLANNING'),
	 (3,'FIRE_BEHAVIOUR_SPECIALIST','PLANNING'),
	 (4,'GIS_SPECIALIST','PLANNING'),
	 (5,'PLANNING_ASSISTANT','PLANNING'),
	 (7,'PLANS_OFFICER','PLANNING'),
	 (8,'PLANS_SECTION_CHIEF','PLANNING'),
	 (9,'REHAB_SPECIALIST','PLANNING'),
	 (10,'RESOURCE_UNIT_LEADER','PLANNING'),
	 (11,'SITUATION_UNIT_LEADER','PLANNING'),
	 (12,'ASSET_MANAGEMENT','LOGISTICS'),
	 (13,'CAMP_MANAGER','LOGISTICS'),
	 (14,'COMMUNICATION_UNIT_LEADER','LOGISTICS'),
	 (15,'CONTRACT_MONITOR','LOGISTICS'),
	 (16,'DISPATCHER','LOGISTICS'),
	 (17,'FACILITIES_UNIT_LEADER','LOGISTICS'),
	 (18,'FOOD_UNIT_LEADER','LOGISTICS'),
	 (19,'GROUND_SUPPORT_UNIT_LEADER','LOGISTICS'),
	 (20,'LOGISTICS_ASSISTANT','LOGISTICS'),
	 (21,'LOGISTICS_OFFICER','LOGISTICS'),
	 (22,'LOGISTICS_SECTION_CHIEF','LOGISTICS'),
	 (23,'MEDICAL_UNIT_LEADER','LOGISTICS'),
	 (24,'SERVICE_BRANCH_DIRECTOR','LOGISTICS'),
	 (25,'SUPPLY_UNIT_LEADER','LOGISTICS'),
	 (26,'SUPPORT_BRANCH_DIRECTOR','LOGISTICS'),
	 (27,'WAREHOUSE_MANAGER','LOGISTICS'),
	 (28,'ACCOUNTS_PAYABLE','FINANCE_ADMIN'),
	 (29,'COMPENSATION_CLAIMS_UNIT_LEADER','FINANCE_ADMIN'),
	 (30,'CONTRACT_ADMINISTRATION','FINANCE_ADMIN'),
	 (31,'COST_UNIT_LEADER','FINANCE_ADMIN'),
	 (32,'FINANCE_ASSISTANT','FINANCE_ADMIN'),
	 (33,'FINANCE_LIAISON','FINANCE_ADMIN'),
	 (34,'FINANCE_OFFICER','FINANCE_ADMIN'),
	 (35,'FINANCE_SECTION_CHIEF','FINANCE_ADMIN'),
	 (36,'PROCUREMENT_UNIT_LEADER','FINANCE_ADMIN'),
	 (37,'TIME_RECORDER','FINANCE_ADMIN'),
	 (38,'TIME_UNIT_LEADER','FINANCE_ADMIN'),
	 (39,'DIVISION_SUPERVISOR','OPERATIONS'),
	 (40,'EQUIPMENT_BRANCH_DIRECTOR','OPERATIONS'),
	 (41,'EQUIPMENT_GROUP_SUPERVISOR','OPERATIONS'),
	 (42,'LINE_LOCATOR','OPERATIONS'),
	 (43,'STRIKE_TEAM_LEADER','OPERATIONS'),
	 (44,'TASK_FORCE_LEADER','OPERATIONS'),
	 (45,'INFORMATION_ASSISTANT','COMMAND'),
	 (46,'INFORMATION_OFFICER','COMMAND'),
	 (47,'LIAISON_OFFICER','COMMAND'),
	 (48,'SAFETY_OFFICER','COMMAND'),
	 (49,'AVIATION_ASSISTANT','AVIATION'),
	 (50,'HELI_COORDINATOR','AVIATION'),
	 (51,'HELIBASE_MANAGER','AVIATION');`;

export const certsSql = `insert into bcws_certification (id, name) values 
        (1, 'Forklift - Certified'),
        (2, 'Psychological First Aid (PFA)'),
        (3, 'Radio Operator'),
        (4, 'Volunteer Fire Dept'),
        (5, 'Quad/ATV'),
        (6, 'Food Safe Level I'),
        (7, 'Food Safe Level II'),
        (8, 'OFA I'),
        (9, 'OFA II'),
        (10, 'OFA III')
        `;

export const toolsSql = `insert into bcws_tools (id,  name)
        values
        (1, 'ADOBE'),
        (2, 'CAS'),
        (3, 'DEC'),
        (4, 'EXCEL'),
        (5, 'FACE'),
        (6, 'IMIS'),
        (7, 'RRT'),
        (8, 'VISIO')`;



//TODO Update this when we have all of the fire centres/regions
export const joinedLocationsSql = `
        INSERT INTO public.location (id,fire_centre,region,location_name) 
         VALUES
	 (28,'CARIBOO','NEA','Williams Lake'),
	 (20,'CARIBOO','NEA','Quesnel'),
	 (62,'CARIBOO',NULL,'Alexis Creek'),
	 (27,'COASTAL','HQ','Victoria'),
	 (25,'COASTAL','SWE','Vancouver'),
	 (1,'COASTAL','SWE','Abbotsford'),
	 (18,'COASTAL','VIC','Port Alberni'),
	 (14,'COASTAL','VIC','Nanaimo'),
	 (3,'COASTAL','VIC','Campbell River'),
	 (6,'COASTAL','VIC','Duncan'),
	 (22,'COASTAL','VIC','Sechelt'),
	 (16,'COASTAL','VIC','Parksville'),
	 (63,'COASTAL',NULL,'Boston Bar'),
	 (70,'COASTAL',NULL,'Bella Coola'),
	 (69,'COASTAL',NULL,'Powell River'),
	 (68,'COASTAL',NULL,'Squamish'),
	 (67,'COASTAL',NULL,'Pemberton'),
	 (66,'COASTAL',NULL,'Masset'),
	 (65,'COASTAL',NULL,'Cultus Lake'),
	 (64,'COASTAL',NULL,'Chilliwack'),
	 (21,'KAMLOOPS','CTL','Salmon Arm'),
	 (9,'KAMLOOPS','CTL','Kamloops'),
	 (26,'KAMLOOPS','CTL','Vernon'),
	 (13,'KAMLOOPS','CTL','Merritt'),
	 (17,'KAMLOOPS','CTL','Penticton'),
	 (10,'KAMLOOPS','CTL','Kelowna'),
	 (12,'KAMLOOPS','SWE','Lillooet'),
	 (73,'KAMLOOPS',NULL,'Lytton'),
	 (71,'KAMLOOPS',NULL,'Clearwater'),
	 (72,'KAMLOOPS',NULL,'Princeton'),
	 (23,'NORTHWEST','NWE','Smithers'),
	 (24,'NORTHWEST','NWE','Terrace'),
	 (2,'NORTHWEST','NWE','Burns Lake'),
	 (77,'NORTHWEST',NULL,'Atlin'),
	 (74,'NORTHWEST',NULL,'Houston'),
	 (75,'NORTHWEST',NULL,'Hazelton'),
	 (76,'NORTHWEST',NULL,'Dease Lake'),
	 (78,'NORTHWEST',NULL,'Prince Rupert'),
	 (8,'PRINCE_GEORGE','NEA','Fort Nelson'),
	 (7,'PRINCE_GEORGE','NEA','Fort St. John'),
	 (5,'PRINCE_GEORGE','NEA','Dawson Creek'),
	 (19,'PRINCE_GEORGE','NEA','Prince George'),
	 (29,'PRINCE_GEORGE','NWE','Vanderhoof'),
	 (82,'PRINCE_GEORGE',NULL,'Fort St. James'),
	 (81,'PRINCE_GEORGE',NULL,'Chetwynd'),
	 (80,'PRINCE_GEORGE',NULL,'Blue River'),
	 (79,'PRINCE_GEORGE',NULL,'Valemount'),
	 (83,'PRINCE_GEORGE',NULL,'MacKenzie'),
	 (4,'SOUTHEAST','SEA','Cranbrook'),
	 (15,'SOUTHEAST','SEA','Nelson'),
	 (11,'SOUTHEAST','SEA','Kimberley'),
	 (85,'SOUTHEAST',NULL,'Nakusp'),
	 (88,'SOUTHEAST',NULL,'Grand Forks'),
	 (84,'SOUTHEAST',NULL,'Invermere'),
	 (87,'SOUTHEAST',NULL,'Golden'),
	 (86,'SOUTHEAST',NULL,'Castelgar'),
	 (32,NULL,'HQ','Brentwood Bay'),
	 (41,NULL,'HQ','Esquimalt'),
	 (42,NULL,'HQ','Langford'),
	 (54,NULL,'HQ','Saanich'),
	 (55,NULL,'HQ','Saanichton'),
	 (56,NULL,'HQ','Sidney'),
	 (40,NULL,'CTL','Enderby'),
	 (57,NULL,'CTL','Sorrento'),
	 (44,NULL,'NEA','Mackenzie'),
	 (31,NULL,'NEA','150 Mile House'),
	 (30,NULL,'NEA','100 Mile House'),
	 (39,NULL,'SEA','Elkford'),
	 (34,NULL,'SEA','Bonnington Falls'),
	 (35,NULL,'SEA','Castlegar'),
	 (52,NULL,'SEA','Revelstoke'),
	 (53,NULL,'SWE','Richmond'),
	 (45,NULL,'SWE','Maple Ridge'),
	 (49,NULL,'SWE','North Vancouver'),
	 (48,NULL,'SWE','New Westminster'),
	 (47,NULL,'SWE','Mission'),
	 (37,NULL,'SWE','Coquitlam'),
	 (60,NULL,'SWE','Whistler'),
	 (33,NULL,'SWE','Burnaby'),
	 (58,NULL,'SWE','Surrey'),
	 (43,NULL,'SWE','Langley'),
	 (38,NULL,'VIC','Courtenay'),
	 (61,NULL,'VIC','Sooke'),
	 (59,NULL,'VIC','Ucluelet'),
	 (51,NULL,'VIC','Qualicum Beach'),
	 (50,NULL,'VIC','Port McNeil'),
	 (46,NULL,'VIC','Mill Bay'),
	 (36,NULL,'VIC','Cumberland')`;
