import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1715368811077 implements MigrationInterface {
  name = 'InsertLocationMigration1715368811077';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "emcr_personnel" DROP CONSTRAINT "FK_b086e30a7c5415d59f57bb85ac3"`,
    );

    await queryRunner.query(
      `ALTER TABLE "bcws_personnel" DROP CONSTRAINT "FK_4497c09d4ea63c7187360afc685"`,
    );
    await queryRunner.query(
      `ALTER TABLE "bcws_personnel" DROP CONSTRAINT "FK_874eebc6d744a86c688612247c5"`,
    );

    await queryRunner.query(`
        INSERT into location (fire_centre, region, location_name) values
            ('CARIBOO',	'NEA',	'Quesnel'),
            ('CARIBOO',	'NEA',	'Williams Lake'),
            ('CARIBOO',	'NEA',	'Alexis Creek'),
            ('COASTAL',	'HQ',	'Victoria'),
            ('COASTAL',	'SWE',	'Abbotsford'),
            ('COASTAL',	'SWE',	'Vancouver'),
            ('COASTAL',	'VIC',	'Campbell River'),
            ('COASTAL',	'VIC',	'Duncan'),
            ('COASTAL',	'VIC',	'Nanaimo'),
            ('COASTAL',	'VIC',	'Parksville'),
            ('COASTAL',	'VIC',	'Port Alberni'),
            ('COASTAL',	'VIC',	'Sechelt'),
            ('COASTAL',	'VIC',	'Bella Coola'),
            ('COASTAL',	'SWE',	'Boston Bar'),
            ('COASTAL',	'SWE',	'Chilliwack'),
            ('COASTAL',	'SWE',	'Cultus Lake'),
            ('COASTAL',	'NWE',	'Masset'),
            ('COASTAL',	'SWE',	'Pemberton'),
            ('COASTAL',	'VIC',	'Powell River'),
            ('COASTAL',	'SWE',	'Squamish'),
            ('KAMLOOPS',	'CTL',	'Kamloops'),
            ('KAMLOOPS',	'CTL',	'Kelowna'),
            ('KAMLOOPS',	'CTL',	'Merritt'),
            ('KAMLOOPS',	'CTL',	'Penticton'),
            ('KAMLOOPS',	'CTL',	'Salmon Arm'),
            ('KAMLOOPS',	'CTL',	'Vernon'),
            ('KAMLOOPS',	'SWE',	'Lillooet'),
            ('KAMLOOPS',	'CTL',	'Clearwater'),
            ('KAMLOOPS',	'SWE',	'Lytton'),
            ('KAMLOOPS',	'CTL',	'Princeton'),
            ('NORTHWEST',	'NWE',	'Burns Lake'),
            ('NORTHWEST',	'NWE',	'Smithers'),
            ('NORTHWEST',	'NWE',	'Terrace'),
            ('NORTHWEST',	'NWE',	'Atlin'),
            ('NORTHWEST',	'NWE',	'Dease Lake'),
            ('NORTHWEST',	'NWE',	'Hazelton'),
            ('NORTHWEST',	'NWE',	'Houston'),
            ('NORTHWEST',	'NWE',	'Prince Rupert'),
            ('PRINCE_GEORGE',	'NEA',	'Dawson Creek'),
            ('PRINCE_GEORGE',	'NEA',	'Fort Nelson'),
            ('PRINCE_GEORGE',	'NEA',	'Fort St. John'),
            ('PRINCE_GEORGE',	'NEA',	'Prince George'),
            ('PRINCE_GEORGE',	'NWE',	'Vanderhoof'),
            ('PRINCE_GEORGE',	'CTL',	'Blue River'),
            ('PRINCE_GEORGE',	'NEA',	'Chetwynd'),
            ('PRINCE_GEORGE',	'NEA',	'Fort St. James'),
            ('PRINCE_GEORGE',	'NEA',	'MacKenzie'),
            ('PRINCE_GEORGE',	'NEA',	'Valemount'),
            ('SOUTHEAST',	'SEA',	'Cranbrook'),
            ('SOUTHEAST',	'SEA',	'Kimberley'),
            ('SOUTHEAST',	'SEA',	'Nelson'),
            ('SOUTHEAST',	'SEA',	'Castelgar'),
            ('SOUTHEAST',	'SEA',	'Golden'),
            ('SOUTHEAST',	'SEA',	'Grand Forks'),
            ('SOUTHEAST',	'SEA',	'Invermere'),
            ('SOUTHEAST',	'SEA',	'Nakusp'),
            ('KAMLOOPS',	'CTL',	'Enderby'),
            ('KAMLOOPS',	'CTL',	'Sorrento'),
            ('COASTAL',	'HQ',	'Brentwood Bay'),
            ('COASTAL',	'HQ',	'Esquimalt'),
            ('COASTAL',	'HQ',	'Langford'),
            ('COASTAL',	'HQ',	'Saanich'),
            ('COASTAL',	'HQ',	'Saanichton'),
            ('COASTAL',	'HQ',	'Sidney'),
            ('CARIBOO',	'NEA',	'100 Mile House'),
            ('CARIBOO',	'NEA',	'150 Mile House'),
            ('PRINCE_GEORGE',	'NEA',	'Mackenzie'),
            ('SOUTHEAST',	'SEA',	'Bonnington Falls'),
            ('SOUTHEAST',	'SEA',	'Castlegar'),
            ('SOUTHEAST',	'SEA',	'Elkford'),
            ('SOUTHEAST',	'SEA',	'Revelstoke'),
            ('COASTAL',	'SWE',	'Burnaby'),
            ('COASTAL',	'SWE',	'Coquitlam'),
            ('COASTAL',	'SWE',	'Langley'),
            ('COASTAL',	'SWE',	'Maple Ridge'),
            ('COASTAL',	'SWE',	'Mission'),
            ('COASTAL',	'SWE',	'New Westminster'),
            ('COASTAL',	'SWE',	'North Vancouver'),
            ('COASTAL',	'SWE',	'Richmond'),
            ('COASTAL',	'SWE',	'Surrey'),
            ('COASTAL',	'SWE',	'Whistler'),
            ('COASTAL',	'VIC',	'Courtenay'),
            ('COASTAL',	'VIC',	'Cumberland'),
            ('COASTAL',	'VIC',	'Mill Bay'),
            ('COASTAL',	'VIC',	'Port McNeil'),
            ('COASTAL',	'VIC',	'Qualicum Beach'),
            ('COASTAL',	'VIC',	'Sooke'),
            ('COASTAL',	'VIC',	'Ucluelet')
            ON CONFLICT (location_name) DO UPDATE
            SET region = EXCLUDED.region, fire_centre=excluded.fire_centre;
    `);

    await queryRunner.query(
      `ALTER TABLE "bcws_personnel" ADD CONSTRAINT "FK_874eebc6d744a86c688612247c5" FOREIGN KEY ("work_fire_centre") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "bcws_personnel" ADD CONSTRAINT "FK_4497c09d4ea63c7187360afc685" FOREIGN KEY ("home_fire_centre") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "emcr_personnel" ADD CONSTRAINT "FK_5778c27d09c7f415bd9ab93950f" FOREIGN KEY ("work_location", "work_region") REFERENCES "location"("location_name","region") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "emcr_personnel" ADD CONSTRAINT "FK_b086e30a7c5415d59f57bb85ac3" FOREIGN KEY ("home_location", "home_region") REFERENCES "location"("location_name","region") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // await queryRunner.query(
    //     `ALTER TABLE "bcws_personnel" DROP CONSTRAINT "FK_4497c09d4ea63c7187360afc685"`,
    // );
    // await queryRunner.query(
    //     `ALTER TABLE "bcws_personnel" DROP CONSTRAINT "FK_874eebc6d744a86c688612247c5"`,
    // );
    await queryRunner.query(`
        DELETE FROM location WHERE location_name NOT IN (
            '100 Mile House',
             '150 Mile House',
             'Abbotsford',
             'Brentwood Bay',
             'Burnaby',
             'Burns Lake',
             'Bonnington Falls',
             'Campbell River',
             'Castlegar',
             'Cumberland',
             'Coquitlam',
             'Courtenay',
             'Cranbrook',
             'Dawson Creek',
             'Duncan',
             'Elkford',
             'Enderby',
             'Esquimalt',
             'Fort St. John',
             'Fort Nelson',
             'Kamloops',
             'Kelowna',
             'Kimberley',
             'Langford',
             'Langley',
             'Lillooet',
             'Mackenzie',
             'Maple Ridge',
             'Merritt',
             'Mill Bay',
             'Mission',
             'Nanaimo',
             'Nelson',
             'New Westminster',
             'North Vancouver',
             'Parksville',
             'Penticton',
             'Port Alberni',
             'Port McNeil',
             'Prince George',
             'Qualicum Beach',
             'Quesnel',
             'Revelstoke',
             'Richmond',
             'Saanich',
             'Saanichton',
             'Salmon Arm',
             'Sechelt',
             'Sidney',
             'Smithers',
             'Sorrento',
             'Surrey',
             'Terrace',
             'Ucluelet',
             'Vancouver',
             'Vernon',
             'Victoria',
             'Whistler',
             'Williams Lake',
             'Vanderhoof',
             'Sooke'
            )`);
    await queryRunner.query(`update location set fire_centre = null where location_name in (
            '100 Mile House',
            '150 Mile House',
            'Abbotsford',
            'Brentwood Bay',
            'Burnaby',
            'Burns Lake',
            'Bonnington Falls',
            'Campbell River',
            'Castlegar',
            'Cumberland',
            'Coquitlam',
            'Courtenay',
            'Cranbrook',
            'Dawson Creek',
            'Duncan',
            'Elkford',
            'Enderby',
            'Esquimalt',
            'Fort St. John',
            'Fort Nelson',
            'Kamloops',
            'Kelowna',
            'Kimberley',
            'Langford',
            'Langley',
            'Lillooet',
            'Mackenzie',
            'Maple Ridge',
            'Merritt',
            'Mill Bay',
            'Mission',
            'Nanaimo',
            'Nelson',
            'New Westminster',
            'North Vancouver',
            'Parksville',
            'Penticton',
            'Port Alberni',
            'Port McNeil',
            'Prince George',
            'Qualicum Beach',
            'Quesnel',
            'Revelstoke',
            'Richmond',
            'Saanich',
            'Saanichton',
            'Salmon Arm',
            'Sechelt',
            'Sidney',
            'Smithers',
            'Sorrento',
            'Surrey',
            'Terrace',
            'Ucluelet',
            'Vancouver',
            'Vernon',
            'Victoria',
            'Whistler',
            'Williams Lake',
            'Vanderhoof',
            'Sooke'
        )`);
  }
}
