export enum APP_ENV {
  LOCAL = 'local',
  DEV = 'dev',
  TEST = 'test',
  PROD = 'production',
}

export const ICS_TRAINING_NAME = 'ICS Training';  // Explicitly for ICS training

export const divisionsAndMinistries = [
  { division: "Office of the Chief Forester", ministry: 'FOR' },
  { division: "ntegrated Resource Operations Division", ministry: 'FOR' },
  { division: "imber, Range, and Economics", ministry: 'FOR' },
  { division: "orest Resiliency and Archaeology", ministry: 'FOR' },
  { division: "orth Area", ministry: 'FOR' },
  { division: "outh Area", ministry: 'FOR' },
  { division: "oast Area", ministry: 'FOR' },
  { division: "C Timber Sales", ministry: 'FOR' },
  { division: "C Wildfire", ministry: 'FOR' },
  { division: "Land Use Planning and Cumulative Effects", ministry: 'WLRS' },
  { division: "Resource Stewardship", ministry: 'WLRS' },
  { division: "Water, Fisheries and Coast", ministry: 'WLRS' },
  { division: "Reconciliation, Lands and Natural Resource Policy", ministry: 'WLRS' },
  { division: "Permitting Transformation", ministry: 'WLRS' },
  { division: "Natural Resource Information and Digital Services", ministry: 'WLRS' },
  { division: "Corporate Services for Natural Resource Ministries ", ministry: 'WLRS' },
  { division: "Conservation and Recreation Division", ministry: 'ENV' },
  { division: "Recreation Strategy and Service Transformation", ministry: 'ENV' },
  { division: "Climate Action Secretariat", ministry: 'ENV' },
  { division: "Environmental Protection Division", ministry: 'ENV' },
  { division: "Strategic Services Division", ministry: 'ENV' },
  { division: "Deputy Minister/'/s Office", ministry: 'AF' },
  { division: "Agriculture Resource Division", ministry: 'AF' },
  { division: "Science, Policy, and Inspection Division", ministry: 'AF' },
  { division: "Climate Resilience, Competitiveness and Reconciliation Division", ministry: 'AF' },
  { division: "Corporate Management Services ", ministry: 'AG' },
  { division: "Information Systems", ministry: 'AG' },
  { division: "BC Prosecution Service", ministry: 'AG' },
  { division: "Court Services Branch", ministry: 'AG' },
  { division: "Independent Investigations Office", ministry: 'AG' },
  { division: "Investigation and Standards Office", ministry: 'AG' },
  { division: "Justice Services Branch", ministry: 'AG' },
  { division: "Legal Services Branch", ministry: 'AG' },
  { division: "Multiculturalism and Anti-Racism Branch", ministry: 'AG' },
  { division: "BC Corrections", ministry: 'PSSG' },
  { division: "BC Coroners Service", ministry: 'PSSG' },
  { division: "Cannabis, Consumer Protection and Corporate Policy Branch", ministry: 'PSSG' },
  { division: "Community Safety and Crime Prevention", ministry: 'PSSG' },
  { division: "Gaming Policy and Enforcement Branch", ministry: 'PSSG' },
  { division: "Liquor and Cannabis Regulation Branch", ministry: 'PSSG' },
  { division: "Office of the Fire Commissioner", ministry: 'PSSG' },
  { division: "Policing and Security", ministry: 'PSSG' },
  { division: "RoadSafetyBC", ministry: 'PSSG' },
  { division: "Deputy Minister''s Office", ministry: 'MCF' },
  { division: "Information Services ", ministry: 'MCF' },
  { division: "Service Delivery Division", ministry: 'MCF' },
  { division: "Strategic Integration, Policy & Legislation Division", ministry: 'MCF' },
  { division: "Partnership & Indigenous Engagement", ministry: 'MCF' },
  { division: "Finance & Corporate Services", ministry: 'MCF' },
  { division: "Strategic Services Division", ministry: 'MCF' },
  { division: "Office of the Provincial Director & Aboriginal Services", ministry: 'MCF' },
  { division: "Deputy Minister''s Office", ministry: 'CITZ' },
  { division: "BC Data Service", ministry: 'CITZ' },
  { division: "Connectivity", ministry: 'CITZ' },
  { division: "Corporate Services", ministry: 'CITZ' },
  { division: "Deal Management Office", ministry: 'CITZ' },
  { division: "Government Digital Experience", ministry: 'CITZ' },
  { division: "OCIO - Government Chief Information Officer", ministry: 'CITZ' },
  { division: "OCIO - Corporate Information and Records Management Office", ministry: 'CITZ' },
  { division: "OCIO - Enterprise Services", ministry: 'CITZ' },
  { division: "Procurement and Supply", ministry: 'CITZ' },
  { division: "Real Property", ministry: 'CITZ' },
  { division: "Service BC", ministry: 'CITZ' },
  { division: "Deputy Minister''s Office", ministry: 'ECC' },
  { division: "Child care", ministry: 'ECC' },
  { division: "Education Programs", ministry: 'ECC' },
  { division: "Governance and Analytics", ministry: 'ECC' },
  { division: "Learning", ministry: 'ECC' },
  { division: "Resource Management ", ministry: 'ECC' },
  { division: "Services & Technology", ministry: 'ECC' },
  { division: "DMO and Associate DMO", ministry: 'EMCR' },
  { division: "Corporate Services ", ministry: 'EMCR' },
  { division: "Disaster Recovery ", ministry: 'EMCR' },
  { division: "Disaster Risk Management", ministry: 'EMCR' },
  { division: "Partnerships, Engagement and Legislation", ministry: 'EMCR' },
  { division: "Regional Operations", ministry: 'EMCR' },
  { division: "Deputy Minister''s Office", ministry: 'EMLI' },
  { division: "Electricity and Utility Regulation Division", ministry: 'EMLI' },
  { division: "Energy Decarbonization Division", ministry: 'EMLI' },
  { division: "Energy Resources Division", ministry: 'EMLI' },
  { division: "Responsible Mining and Competitiveness Division", ministry: 'EMLI' },
  { division: "Mines Health, Safety & Enforcement Division", ministry: 'EMLI' },
  { division: "Strategic and Indigenous Partnerships Division", ministry: 'EMLI' },
  { division: "Corporate Services", ministry: 'FIN' },
  { division: "Gender Equity Office", ministry: 'FIN' },
  { division: "Office of the Comptroller General", ministry: 'FIN' },
  { division: "Policy & Legislation Division", ministry: 'FIN' },
  { division: "Provincial Treasury", ministry: 'FIN' },
  { division: "Revenue Division and Anti-Money Laundering Secretariat", ministry: 'FIN' },
  { division: "Treasury Board Staff", ministry: 'FIN' },
  { division: "Deputy Minister''s Office", ministry: 'FIN' },
  { division: "Deputy Minister's Office", ministry: 'HLTH' },
  { division: "Associate Deputy Minister''s Offices", ministry: 'HLTH' },
  { division: "Finance and Corporate Services", ministry: 'HLTH' },
  { division: "Health Sector Information, Analysis and Reporting", ministry: 'HLTH' },
  { division: "Health Sector Information Management / Information Technology", ministry: 'HLTH' },
  { division: "Health Sector Workforce and Beneficiary Services", ministry: 'HLTH' },
  { division: "Hospital and Provincial Health Services", ministry: 'HLTH' },
  { division: "Mental Health and Substance Use", ministry: 'HLTH' },
  { division: "Office of the Provincial Health Officer", ministry: 'HLTH' },
  { division: "Office of the Seniors Advocate", ministry: 'HLTH' },
  { division: "Pharmaceutical, Laboratory and Blood Services", ministry: 'HLTH' },
  { division: "Population and Public Health", ministry: 'HLTH' },
  { division: "Primary Care", ministry: 'HLTH' },
  { division: "Seniors'' Services", ministry: 'HLTH' },
  { division: "Strategic Innovation", ministry: 'HLTH' },
  { division: "Strategy Management and People Office", ministry: 'HLTH' },
  { division: "Deputy Minister''s Office", ministry: 'HOUS' },
  { division: "Housing and Land Use Policy", ministry: 'HOUS' },
  { division: "Homelessness, Partnerships and Housing Supports", ministry: 'HOUS' },
  { division: "Strategy, Governance and Accountability ", ministry: 'HOUS' },
  { division: "Housing Innovations", ministry: 'HOUS' },
  { division: "Deputy Minister''s Office", ministry: 'IRR' },
  { division: "Negotiations & Regional Operations Division", ministry: 'IRR' },
  { division: "Reconciliation Transformation & Strategies Division", ministry: 'IRR' },
  { division: "Strategic Partnerships & Initiatives Division", ministry: 'IRR' },
  { division: "Sustainable Economy", ministry: 'JEDI' },
  { division: "Investment Division", ministry: 'JEDI' },
  { division: "Small Business and Economic Development", ministry: 'JEDI' },
  { division: "Trade and Industry Development Division", ministry: 'JEDI' },
  { division: "Employment Standards", ministry: 'LBR' },
  { division: "Policy & Legislation", ministry: 'LBR' },
  { division: "Labour Division", ministry: 'LBR' },
  { division: "Deputy Minister''s Office", ministry: 'MMHA' },
  { division: "Corporate Services", ministry: 'MMHA' },
  { division: "Child, Youth & mental Health Policy", ministry: 'MMHA' },
  { division: "Provincial Support Office", ministry: 'MMHA' },
  { division: "Substance Use Policy", ministry: 'MMHA' },
  { division: "Treatment & recovery", ministry: 'MMHA' },
  { division: "Deputy Minister''s Office", ministry: 'MUNI' },
  { division: "Immigration Services and Strategic Planning", ministry: 'MUNI' },
  { division: "EFO Management Services", ministry: 'MUNI' },
  { division: "Local Government", ministry: 'MUNI' },
  { division: "Deputy Minister''s Office", ministry: 'PSFS' },
  { division: "Finance, Technology & Management Services", ministry: 'PSFS' },
  { division: "Post-Secondary Policy & Programs", ministry: 'PSFS' },
  { division: "Labour Market Development", ministry: 'PSFS' },
  { division: "Governance, Legislation & Engagement", ministry: 'PSFS' },
  { division: "Employment & Labour Market Services", ministry: 'SDPR' },
  { division: "Corporate Services", ministry: 'SDPR' },
  { division: "Research, Innovation and Policy ", ministry: 'SDPR' },
  { division: "Service Delivery", ministry: 'SDPR' },
  { division: "Accessibility Directorate", ministry: 'SDPR' },
  { division: "Tourism Sector Strategy", ministry: 'TACS' },
  { division: "Arts and Culture", ministry: 'TACS' },
  { division: "Sport and Creative", ministry: 'TACS' },
  { division: "Management Services Division", ministry: 'TACS' },
  { division: "Deputy Minister''s Office", ministry: 'MOTI' },
  { division: "Associate Deputy Ministers", ministry: 'MOTI' },
  { division: "Highways and Regional Services Division", ministry: 'MOTI' },
  { division: "Highways and Regional Services Division: South Coast Region", ministry: 'MOTI' },
  { division: "Highways and Regional Services Division: Southern Interior Region", ministry: 'MOTI' },
  { division: "Highways and Regional Services Division: Northern Region", ministry: 'MOTI' },
  { division: "Policy, Programs and Partnerships Division", ministry: 'MOTI' },
  { division: "Integrated Transportation and Infrastructure Services Division", ministry: 'MOTI' },
  { division: "Strategic and Corporate Priorities Division", ministry: 'MOTI' },
  { division: "Finance and Risk Management Division", ministry: 'MOTI' }]