export const sampleData = {
  '@odata.context':
    'https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/$metadata#Datamart_COREProg_dbo_vw_report_CoreProg_EmployeeData/$entity',
  Action_Date: '2025-03-08',
  Appt_Status: 'Regular',
  Appt_Status_Code: 'R',
  Base_Hourly_RT: null,
  Base_Position: '00102252',
  Base_Position_Title: 'Mgr, Planning and Analysis',
  Base_Supervisor: null,
  Base_Supervisor_Email: null,
  Base_Supervisor_EMPLID: null,
  Business_Phone: null,
  Business_Unit: 'BC100',
  Business_Unit_Description: 'BC Public Service Agency',
  Cell_Phone: null,
  Current_Hourly_RT: 61.239835,
  Current_Position_Number: '00102254',
  Current_Position_Title: 'Mgr, Planning and Analysis',
  Current_Reports_To: '00095946',
  Current_Supervisor: null,
  Current_Supervisor_Email: null,
  Current_Supervisor_EMPLID: null,
  Dept_ID: '100-3511',
  DEPTID_DESCR: 'Data & Insights Office',
  EMPL_RCD: 0,
  Empl_Status: 'Active',
  EMPLID: '126521',
  Employee_Group: 'Management',
  Future_Return_Date: null,
  Grade: 'B2',
  Group_Type: 'Management',
  Hire_Date: '2013-02-09',
  Home_City: 'Victoria',
  Home_Email: 'testemail@yopmail.com',
  Home_Phone: '250/511-2111',
  In_Base_Position: 'Yes',
  Last_Hire_Date: '2015-06-09',
  Layoff_Leave_Stop_Pay_Reason: null,
  Layoff_Leave_Stop_Pay_Start_Date: null,
  Level1: 'HR Planning, Modernization & Corporate Services',
  Level2: 'Information Management & Digital Transformation',
  Level3: 'Data & Insights Office',
  Main_Phone: null,
  Name: 'User,Test',
  Organization: 'BC Public Service Agency',
  Other_Phone: null,
  Sal_Admin_Plan: 'MGT',
  Std_Hours: 35,
  Step: 1,
  Work_City: 'Vancouver',
  Work_Email: 'Test.User@gov.bc.ca',
  Work_Phone: null,
};

export const sampleTrainingData = [
  {
    COURSE: 'ITEM-1995',
    COURSE_TITLE:
      '(BC CORRECTIONS ONLY) Annual Review of the Standards of Conduct for BC Corrections Employees, Oath of Employment and Appropriate Use Policy',
    EMPL_RCD: 0,
    EMPLID: '141414',
    LM_COMPL_DT: '2024-04-15',
  },
  {
    COURSE: 'ITEM-652',
    COURSE_TITLE:
      'IM 117 Information Management: Managing government information, privacy, access to information and security',
    EMPL_RCD: 0,
    EMPLID: '141414',
    LM_COMPL_DT: '2021-07-07',
  },
];
