export enum ButtonTypes {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  TERTIARY = 'TERTIARY',
  SECONDARY_LIGHT = 'SECONDARY_LIGHT',
  TEXT = 'TEXT',
  OUTLINED = 'OUTLINED',
  SOLID = 'SOLID',
}
