export enum ButtonTypes {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  TERTIARY = 'TERTIARY',
  SECONDARY_LIGHT = 'SECONDARY_LIGHT',
  TEXT = 'TEXT',
  TEXT_SECONDARY = 'TEXT_SECONDARY',
  OUTLINED = 'OUTLINED',
  SOLID = 'SOLID',
  SOLID_SECONDARY = 'SOLID_SECONDARY',
}
