export enum Ministry {
  AGRI = 'AGRI',
  AG = 'AG',
  MCF = 'MCF',
  CITZ = 'CITZ',
  ECC = 'ECC',
  EMCR = 'EMCR',
  EMLI = 'EMLI',
  ENV = 'ENV',
  FIN = 'FIN',
  FOR = 'FOR',
  HLTH = 'HLTH',
  HOUS = 'HOUS',
  IRR = 'IRR',
  JEDI = 'JEDI',
  LBR = 'LBR',
  MMHA = 'MMHA',
  MUNI = 'MUNI',
  PSFS = 'PSFS',
  PSSG = 'PSSG',
  SDPR = 'SDPR',
  TAC = 'TAC',
  MOTI = 'MOTI',
  WLRS = 'WLRS',
}
