export enum Ministry {
  AF = 'AF',
  AG = 'AG',
  MCF = 'MCF',
  CITZ = 'CITZ',
  ECC = 'ECC',
  EMCR = 'EMCR',
  EMLI = 'EMLI',
  ENV = 'ENV',
  FIN = 'FIN',
  FOR = 'FOR',
  GCPE = 'GCPE',
  HLTH = 'HLTH',
  HOUS = 'HOUS',
  IRR = 'IRR',
  JEDI = 'JEDI',
  LBR = 'LBR',
  MMHA = 'MMHA',
  MUNI = 'MUNI',
  PREM = 'PREM',
  PSA = 'PSA',
  PSFS = 'PSFS',
  PSSG = 'PSSG',
  SDPR = 'SDPR',
  TACS = 'TACS',
  MOTI = 'MOTI',
  WLRS = 'WLRS',
}
