export enum TravelPreference {
  REMOTE_ONLY = 'REMOTE_ONLY',
  WILLING_TO_TRAVEL_HOME_LOCATION = 'WILLING_TO_TRAVEL_HOME_LOCATION',
  WILLING_TO_TRAVEL_FIRE_ZONE = 'WILLING_TO_TRAVEL_FIRE_ZONE',
  WILLING_TO_TRAVEL_FIRE_CENTRE = 'WILLING_TO_TRAVEL_FIRE_CENTRE',
  WILLING_TO_TRAVEL_REGION = 'WILLING_TO_TRAVEL_REGION',
  WILLING_TO_TRAVEL_ANYWHERE = 'WILLING_TO_TRAVEL_ANYWHERE',
  WILLING_TO_TRAVEL_UNKNOWN = 'WILLING_TO_TRAVEL_UNKNOWN',
}

export enum BcwsTravelPreference {
  REMOTE_ONLY = 'REMOTE_ONLY',
  WILLING_TO_TRAVEL_HOME_LOCATION = 'WILLING_TO_TRAVEL_HOME_LOCATION',
  WILLING_TO_TRAVEL_FIRE_ZONE = 'WILLING_TO_TRAVEL_FIRE_ZONE',
  WILLING_TO_TRAVEL_FIRE_CENTRE = 'WILLING_TO_TRAVEL_FIRE_CENTRE',
  WILLING_TO_TRAVEL_ANYWHERE = 'WILLING_TO_TRAVEL_ANYWHERE',
  WILLING_TO_TRAVEL_UNKNOWN = 'WILLING_TO_TRAVEL_UNKNOWN',
}

export enum EmcrTravelPreference {
  REMOTE_ONLY = 'REMOTE_ONLY',
  WILLING_TO_TRAVEL_HOME_LOCATION = 'WILLING_TO_TRAVEL_HOME_LOCATION',
  WILLING_TO_TRAVEL_REGION = 'WILLING_TO_TRAVEL_REGION',
  WILLING_TO_TRAVEL_ANYWHERE = 'WILLING_TO_TRAVEL_ANYWHERE',
  WILLING_TO_TRAVEL_UNKNOWN = 'WILLING_TO_TRAVEL_UNKNOWN',
}

export enum TravelPreferenceText {
  REMOTE_ONLY = 'Remote only',
  WILLING_TO_TRAVEL_HOME_LOCATION = 'Within home location',
  WILLING_TO_TRAVEL_FIRE_ZONE = 'Within fire zone',
  WILLING_TO_TRAVEL_FIRE_CENTRE = 'Within fire centre',
  WILLING_TO_TRAVEL_REGION = 'Within region',
  WILLING_TO_TRAVEL_ANYWHERE = 'Anywhere',
  WILLING_TO_TRAVEL_UNKNOWN = 'Willing to travel - Unspecified',
}
